[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "raleigh"
version = "0.1.0"
description = "Simple static website generator from markdown with front-matter"
requires-python = ">=3.14"
dependencies = []

[project.scripts]
raleigh = "raleigh.__main__:main"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "ruff>=0.15.13",
    "ty>=0.0.37",
]

[tool.setuptools.packages.find]
include = ["raleigh*"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I001"]
