NAMES_GIVEN = [
    ("Lago", 1),
    ("Mai", 1),
    ("Zhan", 1),
    ("Glain", 1),
    ("Sidura", 1),
    ("Dotani", 1),
    ("Kayu", 1),
    ("Del", 1),
    ("Kendi", 1),
    ("Caldas", 1),
    ("Nakata", 1),
    ("Emelyn", 1),
    ("Neda", 1),
    ("Tanua", 1),
    ("Soveen", 1),
    ("Javyn", 1),
    ("Baku", 1),
    ("Jarek", 1),
    ("Keelan", 1),
    ("Masias", 1),
    ("Cadigan", 1),
    ("Kanno", 1),
    ("Segura", 1),
    ("Gethin", 1),
    ("Setara", 1),
    ("Hennion", 1),
    ("Kimura", 1),
    ("Reese", 1),
    ("Kuron", 1),
    ("Torrens", 1),
    ("Morien", 1),
    ("Basira", 1),
    ("Toran", 1),
    ("Kuno", 1),
    ("Kalidas", 1),
]

NAMES_SUR = [
    ("Silverleaf", 1),
    ("Anviljaw", 1),
    ("Greenbottle", 1),
    ("Moonshadow", 1),
    ("Bloodfist", 1),
    ("Darkheart", 1),
    ("Fireheart", 1),
    ("Ironhide", 1),
    ("Ashveil", 1),
    ("Blackthorn", 1),
    ("Copperfield", 1),
    ("Dustfoot", 1),
    ("Emberwick", 1),
    ("Frostbeard", 1),
    ("Goldvein", 1),
    ("Holloway", 1),
    ("Ironbound", 1),
    ("Longshadow", 1),
    ("Nightstrider", 1),
    ("Oakhart", 1),
    ("Quickthorn", 1),
    ("Roughhewn", 1),
    ("Silvermane", 1),
    ("Trueblade", 1),
]

TITLES = [
    ("Baron", 1),
    ("Lady", 1),
    ("Lord", 1),
    ("Elder", 1),
    ("Reverend", 1),
    ("Sheriff", 1),
    ("Master", 1),
    ("Mistress", 1),
    ("Doctor", 1),
    ("Sergeant", 1),
    ("Madam", 1),
    ("Sir", 1),
    ("Dame", 1),
    ("Archmage", 1),
    ("Spy", 1),
]

SPECIES = {
    "Human": 3,
    "Elf": 3,
    "Dwarf": 2,
    "Halfling": 2,
    "Orc": 2,
    "Hag": 1,
    "Ogre": 1,
    "Troll": 1,
    "Lizardman": 1,
    "Gnome": 1,
}

ROLES = {
    "Cleric": 1,
    "Fighter": 1,
    "Rogue": 1,
    "Ranger": 1,
    "Magic User": 1,
}

TRAITS = {
    "Acrobatic": 1,
    "Agile": 1,
    "Alchemist": 1,
    "Beast Speaker": 1,
    "Blacksmith": 1,
    "Brawler": 1,
    "Charismatic": 1,
    "Climber": 1,
    "Crafty": 1,
    "Dark Vision": 1,
    "Deceptive": 1,
    "Diplomatic": 1,
    "Engineer": 1,
    "Gambler": 1,
    "Healer": 1,
    "Intimidating": 1,
    "Linguist": 1,
    "Lock Picker": 1,
    "Marksman": 1,
    "Melee Master": 1,
    "Navigator": 1,
    "Negotiator": 1,
    "Nimble Fingers": 1,
    "Outdoorsy": 1,
    "Perceptive": 1,
    "Performer": 1,
    "Runesmith": 1,
    "Stealthy": 1,
    "Strong": 1,
    "Swordmaster": 1,
    "Tracker": 1,
    "Trapmaster": 1,
}

BUILDS = {
    "lithe": 1,
    "stocky": 1,
    "broad-shouldered": 1,
    "willowy": 1,
    "muscular": 1,
    "portly": 1,
    "gaunt": 1,
    "stooped": 1,
    "athletic": 1,
    "slight": 1,
    "imposing": 1,
    "massive": 1,
}

HEIGHTS = {
    "short": 1,
    "average": 2,
    "tall": 2,
    "very tall": 1,
    "diminutive": 1,
}

SKINS = {
    "pale": 2,
    "fair": 2,
    "olive": 2,
    "bronzed": 2,
    "dark": 2,
    "ruddy": 1,
    "sallow": 1,
    "weathered": 2,
    "freckled": 2,
    "ash-gray": 1,
    "silver-tinged": 1,
    "ebony": 1,
    "dark green": 1,
    "grey": 1,
    "red": 1,
}

HAIR_COLORS = {
    "black": 2,
    "brown": 3,
    "auburn": 1,
    "chestnut": 1,
    "blonde": 2,
    "red": 1,
    "gray": 2,
    "white": 1,
    "silver": 1,
    "copper": 1,
    "raven": 1,
    "sandy": 1,
}

HAIR_STYLES = {
    "long and flowing": 1,
    "cropped short": 1,
    "in a tight bun": 1,
    "shaved on one side": 1,
    "braided": 2,
    "in a ponytail": 1,
    "messy and unkempt": 1,
    "elaborate": 1,
    "receding": 1,
    "bald": 1,
    "thick sideburns": 1,
    "mohawk": 1,
    "tangled": 1,
}

EYES = {
    "blue": 2,
    "green": 3,
    "hazel": 2,
    "brown": 3,
    "gray": 1,
    "amber": 1,
    "violet": 1,
    "black": 1,
    "gold-flecked": 1,
    "pale": 1,
    "glowing red": 1,
}

FACES = {
    "angular": 1,
    "round": 1,
    "weathered": 2,
    "soft": 1,
    "sharp": 1,
    "scarred": 1,
    "bearded": 2,
    "clean-shaven": 2,
    "narrow": 1,
    "square-jawed": 1,
    "hollow-cheeked": 1,
}

NOTABLE_FEATURES = {
    "long scar across left cheek": 1,
    "missing tooth": 1,
    "intricate tattoos on forearms": 1,
    "golden earrings": 1,
    "burn marks on hands": 1,
    "distinctive mole": 1,
    "walks with a limp": 1,
    "missing finger": 1,
    "eye patch": 1,
    "broken nose": 1,
    "piercing gaze": 1,
    "melodic voice": 1,
    "nervous twitch": 1,
    "deep laugh": 1,
    "calloused hands": 1,
    "ornate cane": 1,
    "hunched from old injury": 1,
    "bushy beard": 1,
    "constant scowl": 1,
    "warm smile": 1,
}

CLOTHING = {
    "travel-stained cloak": 2,
    "leather jerkin": 2,
    "fine robes": 1,
    "patched work clothes": 1,
    "military uniform": 1,
    "priestly vestments": 1,
    "merchant's finery": 1,
    "torn rags": 1,
    "studded leather": 1,
    "apron over simple clothes": 1,
    "hooded cloak": 1,
    "armor bearing a house sigil": 1,
    "rusty chainmail": 1,
}

MANNERISMS = {
    "speaks in a whisper": 1,
    "loud and boisterous": 1,
    "avoids eye contact": 1,
    "gestures wildly when talking": 1,
    "uses flowery language": 1,
    "blunt to the point of rudeness": 1,
    "nervous laugher": 1,
    "always humming or whistling": 1,
    "pauses frequently to think": 1,
    "finishes others' sentences": 1,
    "strokes chin when thinking": 1,
    "cracks knuckles constantly": 1,
    "never breaks character": 1,
    "mutters in a forgotten tongue": 1,
}

QUIRKS = {
    "collects interesting stones": 1,
    "mutters to self": 1,
    "refuses to say certain words": 1,
    "obsessive about cleanliness": 1,
    "hoards string and twine": 1,
    "talks to animals": 1,
    "always knows the time": 1,
    "hates magic": 1,
    "refuses to sit with back to door": 1,
    "convinced they're cursed": 1,
    "compulsive liar about small things": 1,
    "cannot abide lies": 1,
    "counts everything": 1,
    "collects rune stones": 1,
}

PROFESSIONS = {
    "enchantress": 1,
    "blacksmith": 1,
    "farmer": 1,
    "ranger": 1,
    "warlord": 1,
    "sorceress": 1,
    "gladiator": 1,
    "mercenary": 1,
    "innkeeper": 1,
    "merchant": 1,
    "guard": 1,
    "soldier": 1,
    "priest": 1,
    "thief": 1,
    "alchemist": 1,
    "scholar": 1,
    "healer": 1,
    "sage": 1,
    "minstrel": 1,
    "sailor": 1,
    "carpenter": 1,
    "hunter": 1,
    "jeweler": 1,
    "herbalist": 1,
    "tailor": 1,
    "baker": 1,
    "brewer": 1,
    "cartographer": 1,
    "rune carver": 1,
    "dwarf trader": 1,
}

GOALS = {
    "uncover ancient magical artifacts": 1,
    "create the finest weapons in the land": 1,
    "provide for their family": 1,
    "protect the forests and wilderness": 1,
    "unite the orc tribes into an empire": 1,
    "spread chaos and fear": 1,
    "prove themself the strongest warrior": 1,
    "earn riches through battle": 1,
    "perfect their craft": 1,
    "discover ancient knowledge": 1,
    "gain political power": 1,
    "find a cure for a sick relative": 1,
    "prove their worth": 1,
    "escape their past": 1,
    "rebuild their family name": 1,
    "find true love": 1,
}

SECRETS = {
    "owes a dangerous debt": 1,
    "made a pact with a dark entity": 1,
    "is a spy for a rival faction": 1,
    "hidden noble heritage": 1,
    "is wanted for a crime they didn't commit": 1,
    "knows the location of a lost treasure": 1,
    "is being blackmailed": 1,
    "has a forbidden love": 1,
    "is not who they appear to be": 1,
    "witnessed something terrible": 1,
    "carries a powerful cursed item": 1,
    "is immune to a common poison": 1,
    "can speak with the dead": 1,
    "binds runes in secret": 1,
}

WEAPONS = {
    "Morningstar": 1,
    "Staff": 1,
    "Javelin": 1,
    "Spear": 1,
    "Battle Axe": 1,
    "Long Sword": 1,
    "Warhammer": 1,
    "Halberd": 1,
    "Sling": 1,
    "Pistol Crossbow": 1,
    "Crossbow": 1,
    "Bow": 1,
    "Dagger": 1,
    "Short Sword": 1,
    "Hand Axe": 1,
    "Mace": 1,
    "Flail": 1,
    "Club": 1,
    "Shield": 1,
    "Scimitar": 1,
}

GEAR = {
    "Rope (50')": 1,
    "Rations (3 days)": 1,
    "Spyglass": 1,
    "Grappling Hook": 1,
    "Climbing Gear": 1,
    "2-Person Tent": 1,
    "Cooking Kit": 1,
    "Caltrops (20)": 1,
    "Lockpicks": 1,
    "Bedroll": 1,
    "Flint & Steel": 1,
    "Belt Pouch": 1,
    "Rucksack": 1,
    "Torch (3)": 1,
    "Waterskin": 1,
    "Alchemy Kit": 1,
    "Holy Symbol": 1,
    "Camp Kit": 1,
    "Incense": 1,
    "Hourglass": 1,
    "Soap": 1,
    "Mirror": 1,
    "Fishing Rod": 1,
    "Net": 1,
    "Playing Cards": 1,
    "Book": 1,
}

RUNES = {
    "Air": 1,
    "Earth": 1,
    "Fire": 1,
    "Mind": 1,
    "Water": 1,
    "Body": 1,
    "Dead": 1,
    "Nature": 1,
    "Spirit": 1,
}
