EVENT_TYPES = {
    "Combat": 2,
    "Social": 2,
    "Discovery": 2,
    "Hazard": 1,
    "Ambush": 1,
    "Betrayal": 1,
    "Natural Phenomenon": 1,
    "Arrival": 1,
    "Theft": 1,
    "Accident": 1,
    "Negotiation": 1,
    "Festival": 1,
}

EVENT_TRIGGERS = {
    "strange lights appear at a ruined tower": 1,
    "a merchant ship drifts into harbor": 1,
    "standing stones are stained with blood": 1,
    "orc activity increases in the mountain pass": 1,
    "a deathly-pale ship arrives at dawn": 1,
    "an ominous black tower emits strange sounds": 1,
    "farmers go missing near the old ruins": 1,
    "a crate of black ichor contaminates the docks": 1,
    "a warlord unites the chaotic tribes": 1,
    "the druids have not been seen in weeks": 1,
    "dwarf traders report attacks on the pass": 1,
    "a valuable item goes missing": 1,
    "a stranger seeks shelter from the storm": 1,
    "a secret is accidentally revealed": 1,
}

EVENT_PARTICIPANTS = {
    "local townsfolk": 1,
    "a wandering adventurer": 1,
    "a noble and their entourage": 1,
    "members of a guild": 1,
    "a religious order": 1,
    "a band of outlaws": 1,
    "merchant caravan": 1,
    "military patrol": 1,
    "village elders": 1,
    "foreign diplomats": 1,
    "common criminals": 1,
    "a mysterious cult": 1,
    "hunters from the wilds": 1,
    "an eccentric inventor": 1,
    "orc raiders": 1,
    "dwarf traders": 1,
    "a druid circle": 1,
}

EVENT_COMPLICATIONS = {
    "the weather turns foul": 1,
    "someone has the wrong information": 1,
    "a third party has their own agenda": 1,
    "time is running out": 1,
    "resources are scarce": 1,
    "a key person is unavailable": 1,
    "there's a misunderstanding": 1,
    "old grudges resurface": 1,
    "a valuable item is a fake": 1,
    "someone is watching secretly": 1,
    "the obvious solution is a trap": 1,
    "dark magic is involved": 1,
}

EVENT_ENVIRONMENTS = {
    "heavy rain": 1,
    "fog so thick you can barely see": 1,
    "oppressive heat": 1,
    "biting cold": 1,
    "eerie silence": 1,
    "howling wind": 1,
    "unseasonably pleasant weather": 1,
    "smoke on the horizon": 1,
    "strange lights in the sky": 1,
    "unusual animal behavior": 1,
    "ground trembles slightly": 1,
    "sulfur smell on the air": 1,
}

LOCATION_TYPES = {
    "Ruined Tower": 2,
    "Mountain Pass": 1,
    "Standing Stones": 1,
    "Verdant Forest": 1,
    "Port Town": 1,
    "Abandoned Ship": 1,
    "Tavern": 1,
    "Dungeon": 1,
    "Temple": 1,
    "Market Square": 1,
    "Forest Clearing": 1,
    "Merchant Shop": 1,
    "Town Hall": 1,
    "Harbor": 1,
    "Abandoned Mine": 1,
    "Watchtower": 1,
    "Cave": 1,
    "Fortress": 1,
    "Hidden Grove": 1,
    "Cemetery": 1,
    "Deepwood Forest": 1,
    "Sacred Grove": 1,
}

LOC_PREFIXES = {
    "Old": 1,
    "New": 1,
    "High": 1,
    "Deep": 1,
    "Broken": 1,
    "Iron": 1,
    "Silver": 1,
    "Dark": 1,
    "Fallen": 1,
    "Golden": 1,
    "Crimson": 1,
    "Frost": 1,
    "Ash": 1,
    "Thorn": 1,
    "Sundered": 1,
    "Winter": 1,
    "Dragon": 1,
}

LOC_SUFFIXES = {
    "Hollow": 1,
    "Pass": 1,
    "Gate": 1,
    "Watch": 1,
    "Mouth": 1,
    "Falls": 1,
    "Reach": 1,
    "Crest": 1,
    "Deep": 1,
    "Hold": 1,
    "End": 1,
    "Vale": 1,
    "Peak": 1,
    "Spire": 1,
    "Rise": 1,
    "Wood": 1,
    "Swamp": 1,
    "Citadel": 1,
}

ATMOSPHERES = {
    "ominous darkness simmers below a tranquil veneer": 1,
    "rugged peaks and wooded valleys": 1,
    "cheerful and bustling": 1,
    "eerily quiet": 1,
    "tense and watchful": 1,
    "warm and welcoming": 1,
    "cold and forbidding": 1,
    "mysterious and intriguing": 1,
    "decrepit and decaying": 1,
    "sacred and serene": 1,
    "chaotic and noisy": 1,
    "oppressively dark": 1,
    "strangely peaceful": 1,
}

LOC_FEATURES = {
    "standing stones stained with blood": 1,
    "a ruined wizard's tower": 1,
    "black ichor stains on the deck": 1,
    "a crate marked with strange symbols": 1,
    "an ominous dark tower against the sky": 1,
    "a defensive wall across the pass": 1,
    "a massive oak tree": 1,
    "crumbling stone walls": 1,
    "a weathered statue": 1,
    "faded murals": 1,
    "a secret door hidden behind a bookshelf": 1,
    "an elaborate chandelier": 1,
    "a dried-up well": 1,
    "burned-out torches": 1,
    "fresh flowers on every sill": 1,
}

LOC_POI = {
    "a locked chest under the floorboards": 1,
    "an ancient inscription on the wall": 1,
    "a hidden shrine to a forgotten god": 1,
    "a journal with cryptic entries": 1,
    "a cabinet of strange curiosities": 1,
    "a map pinned to the wall": 1,
    "a collection of unusual weapons": 1,
    "a trapdoor leading down": 1,
    "a strange mushroom circle": 1,
    "an alchemy lab": 1,
    "a bound rune embedded in stone": 1,
    "a forgotten barricade": 1,
}

LOC_SECRETS = {
    "a tunnel leads to the outside": 1,
    "the building is built on an older ruin": 1,
    "someone is hiding in the attic": 1,
    "a ghost is bound to this place": 1,
    "a treasure is buried beneath the floor": 1,
    "the walls contain smuggled goods": 1,
    "a spy meets here regularly": 1,
    "the structure is unstable": 1,
    "a rare flower grows only here": 1,
    "the previous owner was murdered": 1,
    "something slumbers below the sacred grove": 1,
    "a blight spreads from this location": 1,
}

LOC_HAZARDS = {
    "weak floorboards": 1,
    "poisonous spores": 1,
    "unstable ceiling": 1,
    "a pit trap": 1,
    "wild animals lairing here": 1,
    "noxious fumes": 1,
    "razor-sharp debris": 1,
    "slick surfaces": 1,
    "freezing drafts": 1,
    "collapsed passages": 1,
    "black ichor stains": 1,
    "orc patrols nearby": 1,
}
